/** 编辑此文件即可增补词条；slug 同时用于页面锚点与全站搜索链接。 */
export const conceptUpdated = '2026-09-06';
export const groups = [
  { id: 'systems', name: '系统与演化', note: '从要素、关系到整体行为' },
  { id: 'reasoning', name: '逻辑与认知', note: '从概念、证据到可检验的结论' },
  { id: 'markets', name: '投资与市场', note: '理解价格、风险与反馈' },
  { id: 'ai', name: 'AI 与实践', note: '理解模型的能力与边界' },
] as const;
export type Concept = {
  slug: string; name: string; en: string; group: typeof groups[number]['id'];
  definition: string; essentials: string; boundary: string; example: string;
  article: string; related: string[];
  reference?: { title: string; href: string };
};
const reasoning = '/reading/thinking/concept-judgment-reasoning-argument/';
const systems = '/reading/thinking/systems-theory-development-roadmap/';
const options = '/investing/options/option_greek/';
const ai = '/life/ai/ai-system-design-atlas/';
export const concepts: Concept[] = [
  {
    slug: 'system', name: '系统', en: 'System', group: 'systems',
    definition: '在给定边界与观察尺度下，由相互作用的要素及其关系构成、呈现整体行为的集合。分析系统既要描述“有什么”，也要说明“如何连接、如何变化、与环境交换什么”。',
    essentials: '至少明确要素、关系、边界和环境；研究动态问题时还需识别状态、输入、输出与时间尺度。相同要素可以因为连接方式不同而产生不同结果。',
    boundary: '一份清单不自动构成有解释力的系统模型。自然系统也不必具有预先设定的目的；把所有行为都解释为“为了某个目标”容易引入目的论。',
    example: '理解金融市场不能只列出银行、企业和居民，还要追踪它们之间的债权、支付、抵押与信息关系。',
    article: '/reading/economics/financial-system/', related: ['system-boundary', 'feedback', 'emergence'],
  },
  {
    slug: 'system-boundary', name: '系统边界', en: 'System boundary', group: 'systems',
    definition: '分析中用来区分系统内部与外部环境的界限。它决定哪些变量和关系纳入解释，哪些作为外部条件处理，并可以是物理的、组织的或概念性的。',
    essentials: '边界必须服务于研究问题，并说明跨边界的物质、能量、信息或资金流动；时间范围与空间范围同样影响结论。',
    boundary: '边界是分析选择，不等于现实中的绝对隔离。把关键反馈排除在边界之外，可能把系统自身造成的结果误判为外部冲击。',
    example: '只看企业当期利润与把供应商账期、客户留存和环境成本一并纳入，得到的经营判断可能完全不同。',
    article: systems, related: ['system', 'open-system', 'model'],
  },
  {
    slug: 'open-system', name: '开放系统', en: 'Open system', group: 'systems',
    definition: '与环境持续发生交换的系统。热力学中通常指能够交换物质和能量的系统；组织与认知分析中还会讨论信息、资源与人员的交换。',
    essentials: '应具体说明交换对象、通道与约束，以及交换如何维持或改变内部结构。生命体依靠摄取、代谢和排出维持自身。',
    boundary: '开放不等于没有边界。热力学中的“封闭系统”仍可交换能量，而“孤立系统”不交换物质和能量；社会系统中的用法应注明是类比。',
    example: '人体通过食物、氧气、热量与环境交换维持生命；知识组织通过外部证据修正内部认识，是另一层面的开放。',
    article: '/reading/science/human-body-system/', related: ['system-boundary', 'homeostasis', 'self-organization'],
  },
  {
    slug: 'feedback', name: '反馈', en: 'Feedback', group: 'systems',
    definition: '系统的输出或行为结果经由一条因果路径返回，影响后续输入或行为的过程。闭合的因果回路是反馈区别于单向影响的关键。',
    essentials: '强化反馈放大原有变化，调节反馈抵消偏差；实际结果还取决于反馈强度、时滞、资源约束与多个回路之间的竞争。',
    boundary: '正反馈不等于好反馈，负反馈不等于坏反馈。收到一条评价也不必然形成反馈，只有评价改变后续行动并连接到结果时才形成闭环。',
    example: '价格上涨提高抵押品价值，扩大信贷，再推高价格，是强化回路；温控器依据温差调节加热，是调节回路。',
    article: '/investing/cases/creditexpansion/', related: ['homeostasis', 'reflexivity', 'stock-and-flow'],
  },
  {
    slug: 'stock-and-flow', name: '存量与流量', en: 'Stocks and flows', group: 'systems',
    definition: '存量是某一时点累积的量，流量是单位时间内使存量增加或减少的速率。存量的变化由流入与流出的净额累积形成。',
    essentials: '基本关系是“期末存量 = 期初存量 + 期间流入 − 期间流出”。存量和流量的单位不同，例如元与元/月；观测区间必须一致。',
    boundary: '流入减少不等于存量下降：只要流入仍大于流出，存量就继续上升。不能直接把某时点余额与全年交易额当作同类量比较。',
    example: '在没有利息和其他调整时，账户原有 100 元，本月存入 30 元、支出 20 元，期末为 110 元。',
    article: '/reading/economics/macroeconomics-evolution/', related: ['system', 'feedback', 'model'],
  },
  {
    slug: 'emergence', name: '涌现', en: 'Emergence', group: 'systems',
    definition: '多个要素相互作用后，在整体层面出现单个要素不具备的性质或行为模式。这里采用系统分析中的工作性定义，关注微观互动如何产生宏观模式。',
    essentials: '说明涌现需要指出观察尺度、局部规则、互动网络与宏观指标，而不能只把难以理解的现象重新命名。',
    boundary: '涌现并不自动意味着不可解释、不可计算或违反物理规律。哲学中的强涌现与弱涌现有不同主张，本词条不把强涌现视为既定事实。',
    example: '单辆车没有“交通拥堵”这一群体性质，但许多车辆在跟车、制动与道路容量约束下会形成拥堵波。',
    article: '/reading/science/human-brain-evolution/', related: ['system', 'self-organization', 'model'],
  },
  {
    slug: 'self-organization', name: '自组织', en: 'Self-organization', group: 'systems',
    definition: '系统通过内部要素的局部互动形成或维持宏观有序结构，而这种结构并非由外部控制者逐项指定的过程。',
    essentials: '局部规则、相互作用、反馈和环境约束共同塑造宏观结构；许多非平衡自组织过程还依赖持续的能量或物质交换。',
    boundary: '自组织不等于没有规则、没有外部条件，也不保证结果高效、公平或稳定。自组织描述结构的形成机制，涌现描述整体层面的性质，两者相关但不等同。',
    example: '蚂蚁依据局部信息与信息素调整路线，可以形成群体觅食路径，而不需要一只蚂蚁掌握全局地图。',
    article: systems, related: ['emergence', 'open-system', 'feedback'],
  },
  {
    slug: 'homeostasis', name: '稳态调节', en: 'Homeostasis', group: 'systems',
    definition: '生命系统通过持续调节，使某些关键内部变量在环境扰动下保持在可生存范围内的过程。它强调动态维持，而非绝对不变。',
    essentials: '需识别受调变量、感知机制、调节通路与效应器；调节通常涉及反馈，允许波动，也受到能量与生理能力的限制。',
    boundary: '稳态调节不等于热力学平衡，也不等于所有变量恒定。调节成功可能伴随较大内部活动；超出能力范围时，系统仍会失稳。',
    example: '体温升高时通过出汗与皮肤血流变化散热；这不是温度永远不变，而是在一定条件下抵抗偏离。',
    article: '/reading/science/human-body-system/', related: ['feedback', 'open-system'],
  },
  {
    slug: 'concept', name: '概念', en: 'Concept', group: 'reasoning',
    definition: '用于识别、分类与思考对象、性质或关系的认知和语义单位。这里把概念作为思考的基本组成部分；它与词语相关，但不能简单等同于一个词。',
    essentials: '澄清概念时，要交代它指什么、何时适用、与相邻概念有什么差别。必要时区分内涵（判定特征）与外延（适用对象）。',
    boundary: '同一概念可由不同语言表达，同一个词也可能表达多个概念。并非所有自然语言概念都有公认的充分必要条件；原型和家族相似性也是重要解释。',
    example: '“系统”是概念；“金融系统包含信用关系”是在运用概念作出判断，二者不是同一层次。',
    article: reasoning, related: ['judgment', 'inference', 'model'],
    reference: { title: 'Stanford Encyclopedia of Philosophy · Concepts', href: 'https://plato.stanford.edu/entries/concepts/' },
  },
  {
    slug: 'judgment', name: '判断', en: 'Judgment', group: 'reasoning',
    definition: '对某种情况是否成立作出肯定或否定的认知活动。在本站逻辑讨论中，重点是能够表达为命题、接受理由与证据检验的判断。',
    essentials: '应明确主张的对象、条件、时间与量词。“所有”“部分”“可能”“必然”会显著改变判断的强度。判断活动与被判断的命题内容需要区分。',
    boundary: '提问、命令与单独的概念词通常不直接断言事实。判断的确信程度也不等于其真实性；价值判断还需要说明评价标准。',
    example: '“反馈”只是概念；“在其他条件不变时，这个回路放大价格变化”是带有条件的判断。',
    article: reasoning, related: ['concept', 'inference', 'argument'],
  },
  {
    slug: 'inference', name: '推理', en: 'Inference', group: 'reasoning',
    definition: '从一个或多个前提出发，依据某种规则或支持关系得到结论的过程。不同推理类型对结论提供不同强度的支持。',
    essentials: '演绎推理关注结论是否必然随前提成立；归纳根据样本或经验支持一般性结论；溯因比较候选解释，寻找较佳解释。',
    boundary: '一个结论碰巧正确，不证明推理可靠。归纳和溯因一般可被新证据修正；演绎的形式有效也不能保证前提实际为真。',
    example: '“所有 A 都是 B；x 是 A；所以 x 是 B”是演绎结构。“多次观察到 A 后出现 B”则不能单独证明 A 导致 B。',
    article: reasoning, related: ['judgment', 'argument', 'validity'],
  },
  {
    slug: 'argument', name: '论证', en: 'Argument', group: 'reasoning',
    definition: '以一组前提或理由支持某个结论的可表达结构，也指提出、解释与检验这种支持关系的活动。论证使他人能够检查你为什么接受结论。',
    essentials: '完整分析要辨认结论、显式与隐含前提、证据来源及前提到结论的连接方式，并回应足以动摇结论的反例或替代解释。',
    boundary: '论证不等于争吵，也不等于罗列材料。证据真实仍可能与结论无关；语言有说服力也不代表支持关系成立。',
    example: '主张一项政策有效，需要给出比较基准、结果数据与排除主要替代解释的理由，而不是只展示实施后的增长。',
    article: reasoning, related: ['inference', 'validity', 'model'],
  },
  {
    slug: 'validity', name: '有效性与健全性', en: 'Validity and soundness', group: 'reasoning',
    definition: '在经典演绎逻辑语境中，有效论证不允许出现“所有前提为真而结论为假”的情形；健全论证则既有效，前提又确实为真。',
    essentials: '有效性检查前提与结论的逻辑关系；健全性还要求检查前提的真实性。评价经验研究时，还要明确其“效度”是否使用了另一种专业含义。',
    boundary: '有效不等于结论在现实中一定为真；前提有假时，有效论证也可能得到假结论。归纳推理通常按支持强弱评价，不能机械套用演绎标准。',
    example: '“所有鱼都会飞；鲤鱼是鱼；所以鲤鱼会飞”形式有效，但因第一前提为假而不健全。',
    article: '/reading/thinking/logic-system-evolution/', related: ['inference', 'argument'],
    reference: { title: 'Stanford Encyclopedia of Philosophy · Classical Logic', href: 'https://plato.stanford.edu/entries/logic-classical/' },
  },
  {
    slug: 'model', name: '模型', en: 'Model', group: 'reasoning',
    definition: '为描述、解释、预测或干预某个对象而建立的有选择的表示。模型可以是概念图、数学方程、计算程序或实物结构，其取舍取决于具体目的。',
    essentials: '说明研究对象、假设、变量、关系、参数、适用范围与验证方式。模型输出是这些条件共同作用的结果，不能脱离条件解读。',
    boundary: '模型不是现实的完整复制；拟合历史数据也不保证解释正确或未来有效。需要区分描述相关性的模型与支持因果干预的模型。',
    example: '存量—流量图适合追踪累积过程，因果回路图适合整理反馈结构，但一张回路图本身并不能给出精确数值预测。',
    article: '/reading/thinking/cognitive-operating-system/', related: ['system-boundary', 'argument', 'stock-and-flow'],
  },
  {
    slug: 'reflexivity', name: '反身性', en: 'Reflexivity', group: 'markets',
    definition: '在索罗斯的金融市场分析语境中，参与者对现实的认知影响其行动，行动又改变被认知的现实，从而使认知与现实相互作用的过程。',
    essentials: '分析时区分认知、决策、市场价格与基础条件，再说明它们之间的双向影响以及在哪些条件下形成自我强化或逆转。',
    boundary: '反身性不等于“想什么就会发生”，也不意味着所有价格波动都是泡沫；融资约束、盈利与外部冲击仍会限制认知对现实的影响。',
    example: '估值上涨改善企业融资条件，融资用于扩张后又改变盈利前景；预期既反映现实，也通过融资通道参与塑造现实。',
    article: '/reading/books/financial-alchemy-systems-analysis/', related: ['feedback', 'model'],
  },
  {
    slug: 'delta', name: 'Delta', en: 'Delta · 一阶价格敏感度', group: 'markets',
    definition: '在其他定价变量保持不变时，期权理论价格对标的价格的一阶变化率。它用于近似估计标的发生小幅价格变化时，期权价格的变化。',
    essentials: '局部近似为 ΔV ≈ Delta × ΔS；需说明报价单位、合约乘数与头寸方向，组合 Delta 还要按数量加总。',
    boundary: 'Delta 会随价格、时间和波动率改变，不是固定倍数，也不能无条件当成真实世界中的获利概率。Delta 中性仍暴露于其他风险。',
    example: '若每单位期权报价的 Delta 为 0.5，标的上涨 1 元，其他条件不变且变化足够小时，期权报价约上涨 0.5 元。',
    article: options, related: ['gamma', 'implied-volatility', 'model'],
    reference: { title: 'OIC · Volatility & the Greeks', href: 'https://prd-web.optionseducation.org/advancedconcepts/volatility-the-greeks' },
  },
  {
    slug: 'gamma', name: 'Gamma', en: 'Gamma · 二阶价格敏感度', group: 'markets',
    definition: '在其他变量保持不变时，Delta 对标的价格的变化率，也是期权价格对标的价格的二阶导数。它刻画价格敏感度本身如何变化。',
    essentials: '局部近似为 ΔDelta ≈ Gamma × ΔS。理解组合 Gamma 必须同时考虑持仓方向、合约数量、期限与行权价。',
    boundary: '单份期权的 Gamma 不等于市场总 Gamma 敞口。市场敞口估计常依赖持仓方向假设，不能仅凭一个符号就断定市场必涨或必跌。',
    example: '若 Delta 为 0.50、Gamma 为 0.04，标的小幅上涨 1 个价格单位后，Delta 约为 0.54；这只是局部近似。',
    article: '/investing/options/gamma-atlas/', related: ['delta', 'implied-volatility'],
    reference: { title: 'OIC · Gamma', href: 'https://prd-web.optionseducation.org/advancedconcepts/gamma' },
  },
  {
    slug: 'implied-volatility', name: '隐含波动率', en: 'Implied volatility · IV', group: 'markets',
    definition: '在指定期权定价模型与其他输入后，使模型价格匹配市场期权价格所反推出的波动率参数。通常采用年化表达。',
    essentials: '它随期限、行权价、市场报价与模型选择而变，同一标的可对应一整张波动率曲面。报价包含预期、风险补偿与供求等影响。',
    boundary: '隐含波动率不是已经实现的历史波动率，不保证未来实际波幅，也不单独给出上涨或下跌方向；极端或异常报价可能无法得到合理解。',
    example: '两份同标的、不同到期日的期权，可能反推出不同隐含波动率，因此不能只用一个数字概括全部期权。',
    article: '/investing/options/option-volatility-pricing/', related: ['delta', 'gamma', 'model'],
    reference: { title: 'OIC · Volatility & the Greeks', href: 'https://prd-web.optionseducation.org/advancedconcepts/volatility-the-greeks' },
  },
  {
    slug: 'language-model', name: '大语言模型', en: 'Large language model · LLM', group: 'ai',
    definition: '在大规模语言数据等材料上训练、能够建模词元序列关系并完成语言任务的模型。常见生成式模型依据上下文逐步预测和生成后续词元。',
    essentials: '训练塑造参数，推理时的上下文影响本次输出；聊天产品还可能组合检索、工具、记忆和规则，产品能力不完全来自模型本身。',
    boundary: '语言流畅不等于事实正确。模型参数不是一份可逐条核验的文献数据库；输出能力也不能直接证明它具有人类式理解或意识。',
    example: '同一个模型接入公司文档检索后，可以回答内部资料问题；新增能力来自模型与检索系统的组合。',
    article: ai, related: ['context-window', 'rag', 'hallucination'],
    reference: { title: 'NIST · Introduction to generative AI', href: 'https://pages.nist.gov/REPO/sections/intro/what-is-genai.html' },
  },
  {
    slug: 'context-window', name: '上下文窗口', en: 'Context window', group: 'ai',
    definition: '语言模型在一次处理过程中可接收或维持的上下文容量上限，通常以词元数衡量。具体产品如何分配输入、输出及内部处理预算，要以其说明为准。',
    essentials: '提示、聊天历史、检索材料和工具结果都可能占用上下文。系统可通过截断、摘要或检索选择送入本次请求的材料。',
    boundary: '上下文不是永久记忆，也不等于模型训练知识。容量足够只说明材料可以被容纳，不保证模型准确利用其中每个细节。',
    example: '一段很早的聊天没有被送入当前请求，即使界面上仍可翻到，模型也未必能在本次回答中使用它。',
    article: '/life/ai/harness-config/', related: ['language-model', 'rag'],
  },
  {
    slug: 'rag', name: '检索增强生成', en: 'Retrieval-augmented generation · RAG', group: 'ai',
    definition: '在生成回答前或生成过程中，从外部知识源检索相关材料，并把材料提供给生成模型作为依据的一类方法。它把检索与生成结合起来。',
    essentials: '典型环节包括资料整理、检索、候选筛选、上下文组织、生成和引用核验。答案质量受资料质量、检索覆盖与模型使用材料的能力共同限制。',
    boundary: 'RAG 通常不直接改变模型参数，因而不同于微调。接入资料库不保证检索命中、引用准确或不产生幻觉；访问权限仍需在检索环节执行。',
    example: '回答公司报销问题前，先检索当前制度中的相关条款，再据此作答并给出对应出处。',
    article: ai, related: ['language-model', 'context-window', 'hallucination'],
    reference: { title: 'NIST CSRC · RAG', href: 'https://csrc.nist.gov/glossary/term/rag' },
  },
  {
    slug: 'hallucination', name: 'AI 幻觉', en: 'Hallucination', group: 'ai',
    definition: '生成式 AI 输出看似可信，却与可核查事实或给定来源不一致、或缺乏来源支持的内容。研究中的具体分类与判定标准并不完全统一。',
    essentials: '应区分事实错误与对材料的不忠实表达，针对人物、数字、引文和因果判断逐项核验，并允许模型在证据不足时保留不确定性。',
    boundary: '这个术语不意味着模型有人的知觉体验或有意欺骗；明确要求创作虚构内容时，虚构本身也不构成任务错误。',
    example: '模型给出一篇实际上不存在的论文标题、作者和 DOI，即使格式完整、语言专业，也属于需要核查的生成错误。',
    article: '/life/ai/rules-hooks/', related: ['rag', 'language-model', 'argument'],
    reference: { title: 'Huang et al. · A Survey on Hallucination in Large Language Models', href: 'https://arxiv.org/abs/2311.05232' },
  },
];
