/**
 * Canonical ASCII slugs for migrated pages and public assets.
 *
 * Keep Chinese display titles in content/frontmatter. Only filesystem and URL
 * path segments belong here. Unknown non-ASCII asset names deliberately fail
 * instead of silently producing unreadable or lossy URLs.
 */

export const ROUTE_SLUGS = Object.freeze({
  '动态gamma敞口图': 'dynamic-gamma-exposure-chart',
  '动态对冲': 'dynamic-hedging',
  '期权波动率与定价': 'option-volatility-pricing',
  '付鹏大类资产投研框架': 'fu-peng-macro-asset-research-framework',
  '称重机-demo_report': 'valuation-weigher-demo-report',
  '科目1': 'driving-theory-test',
  '科目3': 'road-driving-test',
  '科目4': 'safe-driving-theory-test',
  '特斯拉-配件-安全座椅': 'tesla-accessories-child-seats',
  '新手': 'beginner-driving-guide',
  '儿童安全座椅': 'child-car-seats',
  '楼盘对比': 'property-comparison',
  '报单': 'order-management',
  '八次危机': 'eight-crises',
  '复杂': 'complexity',
  '历代经济变革得失': 'chinese-economic-reforms-through-history',
  '圣经': 'bible',
  '形式法则': 'laws-of-form',
  '以利为利': 'fiscal-relations-and-local-government',
  '债-5000年债务史': 'debt-the-first-5000-years',
  '债务危机': 'debt-crises',
  '制内市场': 'markets-within-the-system',
  '置身事内': 'inside-chinese-government',
  '中国国家治理的制度逻辑': 'institutional-logic-of-chinese-governance',
  '古今数学思想': 'history-of-mathematical-thought',
  'logos-系统动力学': 'logos-system-dynamics',
  '悖论图谱': 'paradox-atlas',
  '二元悖论的张力-system_dynamics_of_logos-web': 'binary-paradox-logos-system-dynamics',
  '二元悖论的张力-tension-web': 'binary-paradox-tension',
  '科普勒斯顿哲学史': 'copleston-history-of-philosophy',
  '裂缝的两千五百年': 'twenty-five-centuries-of-the-rift',
  '逻各斯原本': 'elements-of-logos',
  '十六组对立连锁反应链': 'sixteen-oppositions-chain-reaction',
  '十六组对立形而上学核心问题': 'sixteen-oppositions-metaphysical-questions',
  '四律逻辑思脉地图-logos-atlas-web': 'four-laws-logos-atlas',
  '四律自指悖论受力结构': 'four-laws-self-reference-paradox',
  '探索生命的意义与价值': 'meaning-and-value-of-life',
  '西方哲学史考察十讲': 'western-philosophy-lectures',
  '西方哲学思想脉络': 'western-philosophy-lineage',
  '中介之死与五次竞标': 'death-of-the-mediator',
  '总弧图支点搬家史': 'grand-arc-fulcrum-shifts',
  '认知操作系统': 'cognitive-operating-system',
  '认知操作系统-四代矩阵': 'cognitive-operating-system-four-generation-matrix',
  '认知操作系统-系统之美': 'cognitive-operating-system-thinking-in-systems',
  '通用五步法': 'universal-five-step-method',
  '销售明细透视台': 'sales-detail-pivot-dashboard',
});

export const ROUTE_MIGRATIONS = Object.freeze([
  ['investing', 'options', '动态gamma敞口图'],
  ['investing', 'options', '动态对冲'],
  ['investing', 'options', '期权波动率与定价'],
  ['investing', 'valuation', '付鹏大类资产投研框架'],
  ['investing', 'valuation', '称重机-demo_report'],
  ['life', 'driving', '科目1'],
  ['life', 'driving', '科目3'],
  ['life', 'driving', '科目4'],
  ['life', 'driving', '特斯拉-配件-安全座椅'],
  ['life', 'driving', '新手'],
  ['life', 'family', '儿童安全座椅'],
  ['life', 'house', '楼盘对比'],
  ['life', 'orders', '报单'],
  ['reading', 'books', '八次危机'],
  ['reading', 'books', '复杂'],
  ['reading', 'books', '历代经济变革得失'],
  ['reading', 'books', '圣经'],
  ['reading', 'books', '形式法则'],
  ['reading', 'books', '以利为利'],
  ['reading', 'books', '债-5000年债务史'],
  ['reading', 'books', '债务危机'],
  ['reading', 'books', '制内市场'],
  ['reading', 'books', '置身事内'],
  ['reading', 'books', '中国国家治理的制度逻辑'],
  ['reading', 'math', '古今数学思想'],
  ['reading', 'philosophy', 'logos-系统动力学'],
  ['reading', 'philosophy', '悖论图谱'],
  ['reading', 'philosophy', '二元悖论的张力-system_dynamics_of_logos-web'],
  ['reading', 'philosophy', '二元悖论的张力-tension-web'],
  ['reading', 'philosophy', '科普勒斯顿哲学史'],
  ['reading', 'philosophy', '裂缝的两千五百年'],
  ['reading', 'philosophy', '逻各斯原本'],
  ['reading', 'philosophy', '十六组对立连锁反应链'],
  ['reading', 'philosophy', '十六组对立形而上学核心问题'],
  ['reading', 'philosophy', '四律逻辑思脉地图-logos-atlas-web'],
  ['reading', 'philosophy', '四律自指悖论受力结构'],
  ['reading', 'philosophy', '探索生命的意义与价值'],
  ['reading', 'philosophy', '西方哲学史考察十讲'],
  ['reading', 'philosophy', '西方哲学思想脉络'],
  ['reading', 'philosophy', '中介之死与五次竞标'],
  ['reading', 'philosophy', '总弧图支点搬家史'],
  ['reading', 'thinking', '认知操作系统'],
  ['reading', 'thinking', '认知操作系统-四代矩阵'],
  ['reading', 'thinking', '认知操作系统-系统之美'],
  ['reading', 'thinking', '通用五步法'],
  ['working', 'amazon', '销售明细透视台'],
].map(([section, subsection, from]) => ({
  section,
  subsection,
  from,
  to: ROUTE_SLUGS[from],
})));

export const PUBLIC_PATH_NAMES = Object.freeze({
  // Public directories not already covered by ROUTE_SLUGS.
  '称重机': 'valuation-weigher',
  '财报': 'financial-reports',
  '动态Gamma敞口图': 'dynamic-gamma-exposure-chart',
  '港股打新': 'hong-kong-ipo',
  '香港近1年港股IPO数据整理及表格输出': 'hong-kong-ipo-data-past-year',
  '会计': 'accounting',
  '图书': 'books',
  '虚拟币': 'crypto',
  '做市商': 'market-making',
  '科目2': 'closed-course-driving-test',
  '色觉': 'color-vision',
  '特斯拉': 'tesla',
  '配件': 'accessories',
  '安全座椅': 'child-car-seats',
  '系统之美': 'thinking-in-systems',
  '债：5000年债务史': 'debt-the-first-5000-years',
  'Logos 系统动力学': 'logos-system-dynamics',
  '二元悖论的张力': 'binary-paradox-tension',
  '四律逻辑思脉地图': 'four-laws-logos-atlas',
  '二元悖论视角': 'binary-paradox-perspective',
  '讲义': 'lecture-notes',
  '论文': 'papers',
  '系统论视角': 'systems-theory-perspective',
  '形式逻辑规则视角': 'formal-logic-perspective',
  '形而上学': 'metaphysics',
  '认知操作系统·四代矩阵': 'cognitive-operating-system-four-generation-matrix',
  '认知操作系统·系统之美': 'cognitive-operating-system-thinking-in-systems',

  // Public files.
  '工程层层分包逻辑图.svg': 'tiered-subcontracting-logic.svg',
  '信用-货币-流动性-关系图.svg': 'credit-money-liquidity-relationship.svg',
  '汇丰香港银行开户邮件.JPG': 'hsbc-hong-kong-account-opening-email.jpg',
  '港股打新.xlsx': 'hong-kong-ipo.xlsx',
  '工作簿1.xlsx': 'workbook-1.xlsx',
  'Screenshot 2025-04-07 at 15-52-03 特朗普关税血洗美股，大输家和幸存者都有谁？ - WSJ.png': '2025-04-07-trump-tariffs-us-stocks-wsj.png',
  'Screenshot 2025-05-15 at 17-39-03 认知偏误列表 - 维基百科，自由的百科全书.png': '2025-05-15-list-of-cognitive-biases-wikipedia.png',
  'Screenshot 2025-10-03 at 13-21-46 《华尔街日报》中国洞察：“中国悖论”：就美中科技竞争答读者问 - WSJ.png': '2025-10-03-china-paradox-us-china-tech-competition-wsj.png',
  'C2.1 倒车入库.jpg': 'c2-1-reverse-parking.jpg',
  'C2.2 侧方停车.jpg': 'c2-2-parallel-parking.jpg',
  'C2.3 曲线行驶.jpg': 'c2-3-curve-driving.jpg',
  'C2.4直角转弯.jpg': 'c2-4-right-angle-turn.jpg',
  '上坡起步.jpg': 'uphill-start.jpg',
  '水头考场科目三评分标准_GA1026_C2自动挡.xlsx': 'shuitou-road-test-scoring-ga1026-c2.xlsx',
  '水头考场路线图-自动挡①③号线.jpg': 'shuitou-test-route-automatic-lines-1-and-3.jpg',
  '水头考场路线图-自动挡②号线.jpg': 'shuitou-test-route-automatic-line-2.jpg',
  '科目四核心知识点_肖肖精华课整理.xlsx': 'safe-driving-theory-key-points.xlsx',
  '驾驶证色弱体检攻略.docx': 'drivers-license-color-vision-exam-guide.docx',
  '色弱检测图特征记忆法（第5套）.pptx': 'color-vision-test-memory-guide-set-5.pptx',
  '色弱检测图特征记忆法（第6套）.pptx': 'color-vision-test-memory-guide-set-6.pptx',
  '八次危机.epub': 'eight-crises.epub',
  '复杂.epub': 'complexity.epub',
  '历代经济变革得失.epub': 'chinese-economic-reforms-through-history.epub',
  '系统之美：决策者的系统思考.epub': 'thinking-in-systems.epub',
  '以利为利：财政关系与地方政府行为.epub': 'fiscal-relations-and-local-government.epub',
  '债：5000年债务史.epub': 'debt-the-first-5000-years.epub',
  '制内市场：中国国家主导型政治经济学.epub': 'markets-within-the-system.epub',
  '置身事内.epub': 'inside-chinese-government.epub',
  '中国国家治理的制度逻辑.epub': 'institutional-logic-of-chinese-governance.epub',
  '古希腊哲学16组二元对立.pptx': 'sixteen-oppositions-in-ancient-greek-philosophy.pptx',
  '古希腊logos四律推演故事线.xlsx': 'ancient-greek-logos-four-laws-storyline.xlsx',
  '探索生命的意义与价值--从虚无中寻找希望与力量 20260111 --简版.pptx': 'meaning-and-value-of-life-20260111-brief.pptx',
  '德国古典哲学家的神学背景.docx': 'theological-background-of-german-classical-philosophers.docx',
  '二元悖论的张力作为系统动力.xlsx': 'binary-paradox-tension-as-system-dynamics.xlsx',
  '16组核心概念二元对立去看古希腊哲学.docx': 'sixteen-core-oppositions-in-ancient-greek-philosophy.docx',
  '16组核心概念二元对立去看近代哲学与启蒙运动-从笛卡尔到康德.docx': 'sixteen-core-oppositions-in-modern-philosophy-descartes-to-kant.docx',
  '核心问题域二元对立看近代哲学与启蒙运动.docx': 'core-problem-oppositions-in-modern-philosophy-and-enlightenment.docx',
  '核心问题域及核心概念20260704(1).pptx': 'core-problems-and-concepts-20260704.pptx',
  '一台机器两个行程——四十一组二元对立看哲学底层思想脉络.docx': 'one-machine-two-journeys-forty-one-oppositions.docx',
  '20260307西方哲学史考察十讲--图腾禁忌与巫术仪式 .pptx': '20260307-totem-taboo-and-magical-rituals.pptx',
  '20260411西方哲学史考察十讲--神话与宗教.pptx': '20260411-myth-and-religion.pptx',
  '20260516西方哲学史考察十讲--古希腊哲学专题讲座.pptx': '20260516-ancient-greek-philosophy.pptx',
  '20260613西方哲学史考察十讲--希腊化至文艺复兴时期哲学.pptx': '20260613-hellenistic-to-renaissance-philosophy.pptx',
  '20260704西方哲学史考察十讲--从笛卡尔到康德.pptx': '20260704-descartes-to-kant.pptx',
  '宇宙观演变及神学哲学领域核心问题图谱.pptx': 'worldview-evolution-theology-philosophy-map.pptx',
  '不可能三角与困难精炼厂——西方哲学史的内在困难、持续努力与内在逻辑.docx': 'impossible-triangle-and-difficulty-refinery.docx',
  '基于四大基本逻辑定律拔插状态的哲学史演化全景图.docx': 'philosophy-evolution-through-four-laws.docx',
  '矿脉、镣铐与手术刀——古希腊、中世纪、近代哲学比较.docx': 'ancient-medieval-modern-philosophy-comparison.docx',
  '确定性供给制度史——从社会发展变迁看西方哲学问题域及其回答的演变.docx': 'institutional-history-of-certainty-supply.docx',
  '一台机器两个行程——自我奠基之不可能作为哲学史的结构定理（论文全稿）.docx': 'impossibility-of-self-foundation-structural-theorem.docx',
  '手稿 (1).jpg': 'manuscript-1.jpg',
  '手稿 (2).jpg': 'manuscript-2.jpg',
  '手稿 (3).jpg': 'manuscript-3.jpg',
  '用现代的系统论的观点去分析和总结逻辑这套系统的发展历史.docx': 'systems-theory-history-of-logic.docx',
  '逻辑四律推论古希腊logos发展.docx': 'four-laws-and-ancient-greek-logos.docx',
  '四律逻辑思脉地图.docx': 'four-laws-logos-atlas.docx',
  '用逻辑学四律去看古希腊logos的发展.docx': 'ancient-greek-logos-through-four-laws.docx',
  'Π.JPG': 'pi.jpg',
  '框架.png': 'framework.png',
  '未来发展力地图（40个思维模型工具）.png': 'future-capability-map-40-thinking-models.png',
  '原框架.png': 'original-framework.png',
  '系统论推演下的德国古典哲学神学史——对《德国古典哲学家的神学背景》的分析与总结.docx': 'systems-theory-analysis-of-german-classical-philosophy-and-theology.docx',
  '用系统论（Systems Theory）的视角来审视《德国古典哲学家的神学背景》.docx': 'german-classical-philosophers-theology-through-systems-theory.docx',
  '广告DOC合集_00-34.docx': 'advertising-doc-collection-00-34.docx',
  '广告PPT合集_00-34.pptx': 'advertising-ppt-collection-00-34.pptx',
  '认知操作系统·四代版本迭代汇编（依诊断集分类重排·足本）.pdf': 'cognitive-operating-system-four-generation-edition-compilation.pdf',
  '房贷还款明细.csv': 'mortgage-payment-details.csv',
  '某某': 'example',
});

export function englishSlugFor(value) {
  return ROUTE_SLUGS[value] ?? value;
}

export function englishPathNameFor(value) {
  const mapped = PUBLIC_PATH_NAMES[value] ?? ROUTE_SLUGS[value] ?? value;
  if (/[^\x00-\x7f]/.test(mapped)) {
    throw new Error(`Missing ASCII URL mapping for path segment: ${JSON.stringify(value)}`);
  }
  return mapped;
}

export function toAsciiPath(value) {
  return String(value).split(/[\\/]+/).map(englishPathNameFor).join('/');
}
